#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/court-listener-sdk-go"

echo "==> Building court-listener-sdk"
go build ./cmd/court-listener-sdk
